[build]
  publish = "."
  command = "bash netlify/build.sh"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# Routes propres pour masquer les extensions .html
[[redirects]]
  from = "/formation"
  to = "/formation.html"
  status = 200

[[redirects]]
  from = "/paiement"
  to = "/paiement.html"
  status = 200

[[redirects]]
  from = "/responsive-demo"
  to = "/responsive-demo.html"
  status = 200

# Redirection par défaut
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions" 